# Generated by Django 3.2.5 on 2021-07-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('vk', models.URLField()),
                ('email', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=12)),
                ('github', models.URLField()),
                ('skills', models.TextField()),
                ('about_me', models.TextField()),
                ('education', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информации',
            },
        ),
    ]
