# Generated by Django 3.2.5 on 2021-08-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
