# Generated by Django 3.2.5 on 2021-08-04 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210721_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='postDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
